language: node_js
node_js:
  - "13.12.0"
install:
  - "npm install"
before_script:
  - "npm run build"
  - "npm start &"
script: "mvn cobertura:cobertura"
  - "npm test"
after_success:
  - bash <(curl -s https://codecov.io/bash)