language: node_js
node_js:
  - "13.12.0"
install:
  - "npm install"
before_script:
  - "npm run build"
  - "npm start &"
script:
  - "npm test"
  
jobs:
  include:
    - script: COVERALLS_FLAG_NAME=test-1 make test-coveralls-1
    - script: COVERALLS_FLAG_NAME=test-2 make test-coveralls-2
